// <auto-generated />
namespace Rooms.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class tip_id_string : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tip_id_string));
        
        string IMigrationMetadata.Id
        {
            get { return "202106061928271_tip_id_string"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
