// <auto-generated />
namespace Rooms.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Removed_NrPaturi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Removed_NrPaturi));
        
        string IMigrationMetadata.Id
        {
            get { return "202107042036032_Removed_NrPaturi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
