// <auto-generated />
namespace Rooms.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Testul1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Testul1));
        
        string IMigrationMetadata.Id
        {
            get { return "202106051455331_Testul1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
